productsSample = [
    "Triết học là gì?",
    "Giải thích về chủ nghĩa duy vật biện chứng",
    "Quy luật phủ định của phủ định là gì?",
    "Sự khác biệt giữa chủ nghĩa duy vật và chủ nghĩa duy tâm",
    "Triết học Mác-Lênin là gì?",
    "Vật chất là gì theo quan điểm triết học?",
    "Ý thức là gì? Nguồn gốc của ý thức",
    "Mối quan hệ giữa vật chất và ý thức",
    "Quy luật chuyển hóa từ lượng sang chất",
    "Quy luật thống nhất và đấu tranh của các mặt đối lập",
    "Phạm trù nguyên nhân và kết quả trong triết học",
    "Phạm trù tất nhiên và ngẫu nhiên",
    "Phạm trú khả năng và hiện thực",
    "Nhận thức là gì? Quá trình nhận thức",
    "Thực tiễn là gì trong triết học?",
    "Mối quan hệ giữa lý luận và thực tiễn",
    "Chân lý khách quan là gì?",
    "Chân lý tương đối và chân lý tuyệt đối",
    "Qui luật cơ bản của chủ nghĩa duy vật biện chứng",
    "Phương pháp luận của triết học Mác-Lênin",
    "Thế giới quan là gì?",
    "Vai trò của triết học trong đời sống",
    "Hình thái kinh tế - xã hội là gì?",
    "Cơ sở hạ tầng và kiến trúc thượng tầng",
    "Lực lượng sản xuất và quan hệ sản xuất",
    "Phương thức sản xuất là gì?",
    "Giai cấp và đấu tranh giai cấp",
    "Nhà nước trong quan điểm triết học Mác",
    "Ý thức xã hội là gì?",
    "Các hình thái ý thức xã hội",
    "Tồn tại xã hội và ý thức xã hội",
    "Vai trò của quần chúng nhân dân trong lịch sử",
    "Vai trò của cá nhân trong lịch sử",
    "Cách mạng xã hội là gì?",
    "Quy luật phát triển của lịch sử xã hội",
    "Chủ nghĩa xã hội khoa học",
    "Chủ nghĩa cộng sản là gì?",
    "Học thuyết về giá trị thặng dư",
    "Quy luật giá trị trong kinh tế",
    "Mâu thuẫn trong chủ nghĩa tư bản",
    "Chủ nghĩa đế quốc là gì?",
    "Sứ mệnh lịch sử của giai cấp công nhân",
    "Đảng cộng sản trong triết học Mác-Lênin",
    "Chuyên chính vô sản là gì?",
    "Dân chủ xã hội chủ nghĩa",
    "Quy luật khách quan trong lịch sử",
    "Phạm trù hình thức và nội dung",
    "Phạm trù bản chất và hiện tượng",
    "Các nguyên lý của chủ nghĩa duy vật biện chứng",
    "Bạn có Honor Magic 3 không?",
    "Xiaomi Mi 11 Ultra có sẵn không?"
]


chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]